### ISSUE TITLE
New Food(BLUE)

### ISSUE THREAD

**Issue by squirrellovespie** [acmpesuecc/SNEK#3]
# New Food(BLUE)
## Description
1. New food of a different color(blue) must be added.
2. It must occur along with the red food and should disappear when the snake eats 2 red blocks(after score increases by 2).
3. It must occur randomly and should not occur more than once every 5 points.
4. The blue food should make the snake move very quickly and make it invulnerable to everything for 5 seconds(game should not end).
<hr>
  
Bounty points allotted : 50
Any further improvements along with bug fixes will be given brownie points. If the
contributor sees any further improvements that can be done to this project, raise an issue.

**Comment by omkarjois** [comment]
Can i work on this issue?

**Comment by squirrellovespie** [comment]
> Can i work on this issue?

Hey, Yes!

**Comment by squirrellovespie** [comment]
> Can I work on this issue?

Yes!

**Comment by HariOmSwarupSA** [comment]
Can I work on this issue!?

**Comment by Adeeshjn** [comment]
I would like to work on this issue. Can I?

**Comment by adithyatg** [comment]
Can I work on this issue??

**Comment by squirrellovespie** [comment]
> Can I work on this issue??

Sure! I will assign it to you :)
